//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenSlate.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoTask
    {
        public string CreatedBy { get; set; }
        public string CreatedFor { get; set; }
        public string Title { get; set; }
        public short EstimatedHours { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public int Id { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
